resources:
- ../../base

namespace: webscraper-dev

namePrefix: dev-
labels:
- pairs:
    environment: development

images:
  - name: webscraper
    newName: wmcdonald/webscraper
    newTag: latest

patches:
- target:
    kind: Deployment
    name: webscraper
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "postgresql://scraper_user:scraper_pass@dev-postgres:5432/scraper_db"
